### ISSUE TITLE
Got an error when building

### ISSUE THREAD

**Issue by Lewin8687** [lucval/dmm-ns-3.17#1]
Hi Lucval, now I am working on ns3 trying to implement openflow on lte. But I got this error during building ns3.
Sometimes is 
../src/openflow/model/openflow-interface.cc: In member function ‘virtual void ns3::ofi::LearningController::ReceiveFromSwitch(ns3::Ptrns3::OpenFlowSwitchNetDevice, ofpbuf*)’:
../src/openflow/model/openflow-interface.cc:815:19: error: ‘struct ofp_action_nw_addr’ has no member named ‘port’
         action[1].port = atport.second;
                   ^
or 

In file included from ./ns3/network-module.h:22:0,
                 from ../src/lte/test/lte-test-pss-ff-mac-scheduler.cc:53:
./ns3/drop-tail-queue.h:35:30: error: invalid use of incomplete type ‘class ns3::Queue’
 class DropTailQueue : public Queue {
                              ^
In file included from ./ns3/epc-helper.h:29:0,
                 from ../src/lte/test/lte-test-pss-ff-mac-scheduler.cc:52:
./ns3/point-to-point-helper.h:34:7: error: forward declaration of ‘class ns3::Queue’
 class Queue;
       ^
In file included from ./ns3/network-module.h:22:0,
                 from ../src/lte/test/lte-test-pss-ff-mac-scheduler.cc:53:
./ns3/drop-tail-queue.h:53:32: error: ‘ns3::DropTailQueue::QueueMode’ has not been declared
   void SetMode (DropTailQueue::QueueMode mode);
                                ^
./ns3/drop-tail-queue.h:60:3: error: ‘QueueMode’ in ‘class ns3::DropTailQueue’ does not name a type
   DropTailQueue::QueueMode GetMode (void);
   ^
./ns3/drop-tail-queue.h:71:3: error: ‘QueueMode’ does not name a type
   QueueMode m_mode;
   ^
In file included from ./ns3/network-module.h:57:0,
                 from ../src/lte/test/lte-test-pss-ff-mac-scheduler.cc:53:
./ns3/red-queue.h:82:25: error: invalid use of incomplete type ‘class ns3::Queue’
 class RedQueue : public Queue
                         ^
In file included from ./ns3/epc-helper.h:29:0,
                 from ../src/lte/test/lte-test-pss-ff-mac-scheduler.cc:52:
./ns3/point-to-point-helper.h:34:7: error: forward declaration of ‘class ns3::Queue’
 class Queue;
       ^
In file included from ./ns3/network-module.h:57:0,
                 from ../src/lte/test/lte-test-pss-ff-mac-scheduler.cc:53:
./ns3/red-queue.h:131:27: error: ‘ns3::RedQueue::QueueMode’ has not been declared
   void SetMode (RedQueue::QueueMode mode);
                           ^
./ns3/red-queue.h:139:3: error: ‘QueueMode’ in ‘class ns3::RedQueue’ does not name a type
   RedQueue::QueueMode GetMode (void);
   ^
./ns3/red-queue.h:206:3: error: ‘QueueMode’ does not name a type
   QueueMode m_mode;
   ^
In file included from ./ns3/network-module.h:22:0,
                 from ../src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc:53:
./ns3/drop-tail-queue.h:35:30: error: invalid use of incomplete type ‘class ns3::Queue’
 class DropTailQueue : public Queue {
                              ^
In file included from ./ns3/epc-helper.h:29:0,
                 from ../src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc:52:
./ns3/point-to-point-helper.h:34:7: error: forward declaration of ‘class ns3::Queue’
 class Queue;
       ^
In file included from ./ns3/network-module.h:22:0,
                 from ../src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc:53:
./ns3/drop-tail-queue.h:53:32: error: ‘ns3::DropTailQueue::QueueMode’ has not been declared
   void SetMode (DropTailQueue::QueueMode mode);
                                ^
./ns3/drop-tail-queue.h:60:3: error: ‘QueueMode’ in ‘class ns3::DropTailQueue’ does not name a type
   DropTailQueue::QueueMode GetMode (void);
   ^
./ns3/drop-tail-queue.h:71:3: error: ‘QueueMode’ does not name a type
   QueueMode m_mode;
   ^
In file included from ./ns3/network-module.h:57:0,
                 from ../src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc:53:
./ns3/red-queue.h:82:25: error: invalid use of incomplete type ‘class ns3::Queue’
 class RedQueue : public Queue
                         ^
In file included from ./ns3/epc-helper.h:29:0,
                 from ../src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc:52:
./ns3/point-to-point-helper.h:34:7: error: forward declaration of ‘class ns3::Queue’
 class Queue;
       ^
In file included from ./ns3/network-module.h:57:0,
                 from ../src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc:53:
./ns3/red-queue.h:131:27: error: ‘ns3::RedQueue::QueueMode’ has not been declared
   void SetMode (RedQueue::QueueMode mode);
                           ^
./ns3/red-queue.h:139:3: error: ‘QueueMode’ in ‘class ns3::RedQueue’ does not name a type
   RedQueue::QueueMode GetMode (void);
   ^
./ns3/red-queue.h:206:3: error: ‘QueueMode’ does not name a type
   QueueMode m_mode;
   ^

Any idea about this? Thank you.

**Comment by lucval** [comment]
Hi,

on which branch are you running this? Have you used the provided deploy script?

Please give more information, a traceback is not enough to debug the issue.

Luca

**Comment by Lewin8687** [comment]
Hi, 

Thanks for your response!

I tried to build openflow branch but didn't use deploy script. I downloaded your source code and openflow part to enable openflow functions. During building, it throw me the following errors.
In file included from ./ns3/network-module.h:22:0,
                 from ../src/lte/examples/lena-simple-epc.cc:24:
./ns3/drop-tail-queue.h:35:30: error: invalid use of incomplete type ‘class ns3::Queue’
 class DropTailQueue : public Queue {
                              ^
In file included from ./ns3/epc-helper.h:29:0,
                 from ../src/lte/examples/lena-simple-epc.cc:22:
./ns3/point-to-point-helper.h:34:7: error: forward declaration of ‘class ns3::Queue’
 class Queue;
       ^
In file included from ./ns3/network-module.h:22:0,
                 from ../src/lte/examples/lena-simple-epc.cc:24:
./ns3/drop-tail-queue.h:53:32: error: ‘ns3::DropTailQueue::QueueMode’ has not been declared
   void SetMode (DropTailQueue::QueueMode mode);
                                ^
./ns3/drop-tail-queue.h:60:3: error: ‘QueueMode’ in ‘class ns3::DropTailQueue’ does not name a type
   DropTailQueue::QueueMode GetMode (void);
   ^
./ns3/drop-tail-queue.h:71:3: error: ‘QueueMode’ does not name a type
   QueueMode m_mode;
   ^
In file included from ./ns3/network-module.h:57:0,
                 from ../src/lte/examples/lena-simple-epc.cc:24:
./ns3/red-queue.h:82:25: error: invalid use of incomplete type ‘class ns3::Queue’
 class RedQueue : public Queue
                         ^
In file included from ./ns3/epc-helper.h:29:0,
                 from ../src/lte/examples/lena-simple-epc.cc:22:
./ns3/point-to-point-helper.h:34:7: error: forward declaration of ‘class ns3::Queue’
 class Queue;
       ^
In file included from ./ns3/network-module.h:57:0,
                 from ../src/lte/examples/lena-simple-epc.cc:24:
./ns3/red-queue.h:131:27: error: ‘ns3::RedQueue::QueueMode’ has not been declared
   void SetMode (RedQueue::QueueMode mode);
                           ^
./ns3/red-queue.h:139:3: error: ‘QueueMode’ in ‘class ns3::RedQueue’ does not name a type
   RedQueue::QueueMode GetMode (void);
   ^
./ns3/red-queue.h:206:3: error: ‘QueueMode’ does not name a type
   QueueMode m_mode;
   ^
Waf: Leaving directory `../dmm-ns-3.17-openflow/build'
Build failed
 -> task in 'lena-simple-epc' failed (exit status 1): 
    {task 139790390310544: cxx lena-simple-epc.cc -> lena-simple-epc.cc.11.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/pango-1.0', '-I/usr/include/gio-unix-2.0', '-I/usr/include/freetype2', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/harfbuzz', '-I/usr/include/libxml2', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_PACKET_H=1', '-DDL=1', '-DXML2=1', '-DHAVE_SQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_GSL=1', '../src/lte/examples/lena-simple-epc.cc', '-c', '-o', 'src/lte/examples/lena-simple-epc.cc.11.o']

---

Then I built master branch, it can be built successfully. Here is a question about the code. In epc-helper.cc, at line 412, "Ptr<LteEnbNetDevice> enb1LteDev = enb1->GetDevice (3)->GetObject<LteEnbNetDevice> ();", why should we get the third device? Cuz when I run my code (based on your full-openflow example), it told me it is out of range. 
I tried to change it to 2, it works. But i got another issue, "msg="method unexpected in state HANDOVER_PREPARATION", file=../src/lte/model/lte-enb-rrc.cc, line=562
terminate called without an active exception
Command ['../ns-3.17/build/scratch/lte-openflow'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>")." So now, I am learning how to use gdb to debug my code errors.

Also I notice that http folder is empty, is it necessary for the handover in lte network integrated with openflow?

Thank you so much!
Lewin

**Comment by lucval** [comment]
Hi,
http module was ignored by git for some reason. It is now fixed thanks for the heads-up.
Your problem though is not related to this module which is used to emulate background traffic on the topology wired links. If you wish to use ns-3 with openflow support please note that you have to include the ofsid built files in your build directory. I will recommend you to use or to just read the deploy script where the MANDATORY steps for setting up the environment are reported.

Hope this will help,
Luca

**Comment by Lewin8687** [comment]
Hi Luca,

Thanks for the help! I used deploy script and it works. You are right, I didn't notice the ofsid...

I run my code but there is an error and I don't quite understand this.
assert failed. cond="index < m_devices.size ()", msg="Device index 3 is out of range (only have 3 devices).", file=../src/network/model/node.cc, line=135
terminate called without an active exception
Command ['/home/ns-3.17-openflow/build/scratch/lte-openflow'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

As I mentioned in the previous comment,  in epc-helper.cc, at line 412, "Ptr enb1LteDev = enb1->GetDevice (3)->GetObject ();". Can you give me some hint why do we want to get the third device? Is there something that I missed?

Thank you!
Lewin

**Comment by Lewin8687** [comment]
Hi Lucval,

Thanks for the help! I deleted the last question cuz I solved that.

Regards,
Lewin

**Comment by Lewin8687** [comment]
Hi lucval,

If I want to upgrade the openflow module to newest version, do you have any suggestion what should I do?

Thank you!
Regards,
Lewin

**Comment by lucval** [comment]
If you mean ofsid there should not be much problems with the upgrade.

If you mean the src/openflow module, my modifications can be found here: https://github.com/lucval/dmm-ns-3.17/commit/373683a073e33cc9cfa83cd17dd7318cc243d68f. You will need to merge the new module and fix the possible conflicts. It can be dramatic though if you jump multiple versions ahead.

Good luck

**Comment by Lewin8687** [comment]
Hi Lucval,

Thank you for your reply! I tried your example, it works perfectly. But when I set "bgActive" to true, which means I want to have the background traffic, then the program is stuck and it doesn't do the handover. Is there something that I missed?

Thanks!
Lewin

**Comment by lucval** [comment]
Do you have an error trace or is the program just stuck? For the latter case let me tell you that background traffic is a really heavy task so I hope you are running this on a machine that can handle it.

**Comment by Lewin8687** [comment]
There is no error, you are right, it is a heavy task. I run it on a virtual machine and it takes a long time. Thanks for the reply!

**Comment by Khulan47** [comment]
Hi Lucval,
../scratch/test.cc:16:29: fatal error: ns3/http-module.h: No such file or directory
 #include "ns3/http-module.h"
                             ^
compilation terminated.
Waf: Leaving directory `/home/khulan/workspace/ns-allinone-3.17/ns-3.17/build'
Build failed

how to solve?

Thanks!
Khulan

**Comment by lucval** [comment]
Looks like a build issue. Clean, re-configure and re-build.
