### ISSUE TITLE
Encounter "this should not happen" error msg when running example

### ISSUE THREAD

**Issue by LancelotGT** [lucval/dmm-ns-3.17#2]
Hi there,

I am trying to run your example http.c in NS-3 3.17. I just copy the http.c directly to scratch/http.c and run with the command "./waf --run scratch/http". The log messages are as follows:

Create nodes.
Create channels.
Setting the address
Install app in server
Run Simulation.
msg="This should not happen", file=../src/http/model/http-server.cc, line=219
terminate called without an active exception
Command ['/nethome/xfeng60/dmm-ns-3.17/build/scratch/http'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>")

By looking into http-server, it seems like the requestsize shouldn't be zero. But this happens even after I explicitly set the "UserRequestSize" for HttpClient. Do you have a workaround for this problem? Any insight would be appreciated.

**Comment by lucval** [comment]
This is an issue in the http module so not pertinent here.
