### ISSUE TITLE
Help to fix!

### ISSUE THREAD

**Issue by tuandd** [lucval/dmm-ns-3.17#4]
Dear Lucval,

I got a problem when building double-nat.cc. 
I find these functions already in lte-helper.cc and lte-helper.h .However, it can not work.
Could you please tell me the way to fix it?

Best regards,

Duy

[ 769/1499] cxx: scratch/handover.cc -> build/scratch/handover.cc.3.o
../scratch/double-nat.cc: In function ‘int main(int, char**)’:
../scratch/double-nat.cc:991:14: error: ‘class ns3::LteHelper’ has no member named ‘CreateController’
   lteHelper->CreateController(natController);
              ^
../scratch/double-nat.cc:994:14: error: ‘class ns3::LteHelper’ has no member named ‘ConnectSocketsIngress’
   lteHelper->ConnectSocketsIngress(natNode1, natNode1->GetObject<Ipv4>()->GetAddress(1,0).GetLocal());
              ^
../scratch/double-nat.cc:997:14: error: ‘class ns3::LteHelper’ has no member named ‘ConnectSocketsIngress’
   lteHelper->ConnectSocketsIngress(natNode2, natNode2->GetObject<Ipv4>()->GetAddress(1,0).GetLocal());
              ^
../scratch/double-nat.cc:1001:14: error: ‘class ns3::LteHelper’ has no member named ‘ConnectSocketsEgress’
   lteHelper->ConnectSocketsEgress(sgiAR2, sgiAR2->GetObject<Ipv4>()->GetAddress(1,0).GetLocal(), epcHelper2->GetUeDefaultGatewayAddress());
              ^
../scratch/double-nat.cc:1006:16: error: ‘class ns3::LteHelper’ has no member named ‘AttachMme’
     lteHelper->AttachMme(sourceMme, epcHelper1->GetUeDefaultGatewayAddress());
                ^
../scratch/double-nat.cc:1007:16: error: ‘class ns3::LteHelper’ has no member named ‘AttachMme’
     lteHelper->AttachMme(sourceMme, epcHelper2->GetUeDefaultGatewayAddress());
                ^
../scratch/double-nat.cc:1010:16: error: ‘class ns3::LteHelper’ has no member named ‘AttachMme’
     lteHelper->AttachMme(sourceMme, epcHelper1->GetUeDefaultGatewayAddress());
                ^
../scratch/double-nat.cc:1011:16: error: ‘class ns3::LteHelper’ has no member named ‘AttachMme’
     lteHelper->AttachMme(targetMme, epcHelper2->GetUeDefaultGatewayAddress());
                ^
../scratch/double-nat.cc:1012:16: error: ‘class ns3::LteHelper’ has no member named ‘ConnectMmes’
     lteHelper->ConnectMmes(sourceMme, targetMme, epcHelper2->GetUeDefaultGatewayAddress());
                ^
../scratch/double-nat.cc:1075:21: error: ‘class ns3::LteHelper’ has no member named ‘S1HandoverRequestMmeRelocation’
          lteHelper->S1HandoverRequestMmeRelocation (Seconds(hoTime), lteVoiceUeContainerHO.Get(i),
                     ^
Waf: Leaving directory `/home/daotd/harry/ans-3.17-master/build'

**Comment by lucval** [comment]
Since the current version of branch double-nat builds with no issues on my system, my suggestion would be to sync your repo, clean your build, re-configure and re-build.
